#!/usr/bin/env python

import sys
import cv2

if len(sys.argv) != 2:
	print "USAGE: imgview <image_filename>"
	exit(1)
	
image = cv2.imread( sys.argv[1] )
if image is None:
	print "ERROR: Invalid image file"
	exit(1)
	
cv2.imshow( sys.argv[1], image )
cv2.waitKey(0)
